PACKAGE_NAME="amd-i2c-enable"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="amd_i2c_enable"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/amd-i2c-enable/1.0/build modules"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/amd-i2c-enable/1.0/build clean"
AUTOINSTALL="yes"
